# Generated by Django 4.0.2 on 2022-02-05 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodBankRequest',
            fields=[
                ('dateLog', models.DateTimeField(auto_created=True)),
                ('requestID', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('mobile', models.CharField(max_length=10)),
                ('blood', models.CharField(max_length=4)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
