# Generated by Django 4.0.2 on 2022-02-05 11:47

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_bloodbankrequest_datelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbankrequest',
            name='userID',
        ),
        migrations.AlterField(
            model_name='bloodbankrequest',
            name='requestID',
            field=models.CharField(default=login.models.getrequestID, max_length=300, primary_key=True, serialize=False),
        ),
    ]
