# Generated by Django 4.0.2 on 2022-02-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_bloodbankrequest_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbankrequest',
            name='checkme',
            field=models.BooleanField(default=False),
        ),
    ]
