# Generated by Django 4.0.2 on 2022-04-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_bloodbankrequest_checkme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbankrequest',
            name='pincode',
            field=models.IntegerField(default='nan', null=True),
        ),
    ]
