# Generated by Django 4.0.2 on 2022-04-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_bloodbankrequest_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbankrequest',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bloodbankrequest',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bloodbankrequest',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodbankrequest',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodbankrequest',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
