# Generated by Django 4.0.2 on 2022-04-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_bloodbankrequest_address_bloodbankrequest_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbankrequest',
            name='pincode',
        ),
    ]
