# Generated by Django 4.0.2 on 2022-02-05 06:22

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registermodel_blood_alter_registermodel_city_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='registermodel',
            managers=[
                ('objects', registration.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
