# Generated by Django 4.0.2 on 2022-04-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_registermodel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='blood',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='pincode',
        ),
    ]
